
[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'numpy']

[tool.cibuildwheel]
skip = [
    "*t-*",
    "cp39-*",
    "cp310-*",
    "cp311-*",
    "*_i686",
    "*win32",
    "*aarch64",
    "*ppc*",
    "*s390x",
    "*android*",
    "*ios*",
    "*pyodide*",
    ]

build = ["*-win_amd64", "*-manylinux*", "*-musllinux*", "*macosx*"]
test-requires = "pytest"
test-command = "pytest {package}/tests"

[tool.cibuildwheel.windows]
config-settings = { "setup-args" = "--vsenv"}  # force use of MSVC instead of MinGW on Windows

[project]
name = 'spheroidalwavefunctions'
version = '0.1.6'
license = "MIT"
license-files = ["license.txt"]
keywords = ["prolate spheroidal wave function", "backscatter", "model"]
authors = [{ name="Gavin Macaulay"}]
description = 'Spheroidal wave functions'
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
	"numpy",
]
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Science/Research',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Topic :: Scientific/Engineering',
]

[project.urls]
Homepage = 'https://github.com/gavinmacaulay/spheroidalwavefunctions'
Documentation = 'https://github.com/gavinmacaulay/spheroidalwavefunctions/blob/master/readme.md'
Repository = 'https://github.com/gavinmacaulay/spheroidalwavefunctions'
